/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkginterface;

import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Gregio
 */
public class GUI extends javax.swing.JFrame {

    public List<Gerente> gerentes = new ArrayList<>();
    public List<Secretaria> secretarias = new ArrayList<>();
    public List<Operador> operadores = new ArrayList<>();
    public List<RegistroPonto> pontos = new ArrayList<>();

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        jButton4.setFocusPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setOpaque(true);
        jButton4.setBackground(Color.RED);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("ID Ponto");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("ID Funcionario");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setText("Registrar Entrada");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Registrar Saida");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Gerente", "Operador", "Secretaria" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jTextField3.setText("ID Ponto");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText(">(Importante)Primeiro Cadastre Funcionarios clicando no botão.\nCada Classe tem 2 funcionarios cadastrados.\nO ID vai de 1 a 6. Sendo 2 por classe Ex. Gerente id: (1)(2); \nOperador (3)(4), Secretaria (5)(6);\n>Registrar Entrada:\nCrie um id ponto, para especificar o ponto, selecione a classe de \nfuncionario e por ultimo o ID do funcionario daquela classe.\nRegistre a Entrada.\n>Registrar Saida:\nApenas digite o ID ponto criado o qual deseja registrar uma\nsaída.\n>Listar Pontos: \nAo clicar ele lista todos os pontos registrados no banco");
        jScrollPane2.setViewportView(jTextArea1);

        jButton3.setText("Listar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Cadastrar Funcionarios");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Informação");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 166, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 81, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        long id = 0;
        long idp = 0;
        String opc;
        RegistroPonto ponto = new RegistroPonto();
        idp = Long.parseLong(jTextField1.getText());
        ponto.setIdRegPonto(idp);
        opc = jList1.getSelectedValue();
        switch (opc) {
            case "Gerente":
                id = Long.parseLong(jTextField2.getText());
                for (Gerente g : gerentes) {
                    if (id == g.getIdFunc()) {
                        ponto.setFunc(g);
                        break;
                    }
                }
                break;
            case "Operador":
                id = Long.parseLong(jTextField2.getText());
                for (Operador o : operadores) {
                    if (id == o.getIdFunc()) {
                        ponto.setFunc(o);
                        break;
                    }
                }
                break;
            case "Secretaria":
                id = Long.parseLong(jTextField2.getText());
                for (Secretaria s : secretarias) {
                    if (id == s.getIdFunc()) {
                        ponto.setFunc(s);
                        break;
                    }
                }
                break;
        }
        LocalDate dataRegistro = LocalDate.now();
        ponto.setDataRegistro(dataRegistro);
        LocalDateTime dataEntrada = LocalDateTime.now();
        ponto.setHoraEntrada(dataEntrada);
        pontos.add(ponto);
        jTextArea1.setText("Ponto Entrada Registrado");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        RegistroPonto ponto = new RegistroPonto();
        long id = Long.parseLong(jTextField3.getText());
        for (RegistroPonto p : pontos) {
            if (p.getIdRegPonto() == id) {
                LocalDateTime dataSaida = LocalDateTime.now();
                p.setHoraSaida(dataSaida);
                jTextArea1.setText("Ponto Saida Registrado");
                break;
            }

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String text = null;
        for (RegistroPonto rp : pontos) {
            if (text == null) {
                text = "Funcionario: " + rp.getFunc().getClass().getSimpleName() + " " + rp.getFunc().getNome() + "\n";
                text = text + "Data Registro: " + rp.getDataRegistro() + "\n";
                text = text + "Horario Entrada: " + rp.getHoraEntrada() + "\n";
                text = text + "Horario Saida: " + rp.getHoraSaida() + "\n";
                text = text + "------------------";
            } else {

                text = text + "\n" + "Funcionario: " + rp.getFunc().getClass().getSimpleName() + " " + rp.getFunc().getNome() + "\n";
                text = text + "Data Registro: " + rp.getDataRegistro() + "\n";
                text = text + "Horario Entrada: " + rp.getHoraEntrada() + "\n";
                text = text + "Horario Saida: " + rp.getHoraSaida() + "\n";
                text = text + "------------------";
            }

        }
        jTextArea1.setText(text);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed

    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        cadOperdor();
        cadGerente();
        cadSecretaria();
        jTextArea1.setText("Cadastrados");

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String inform;
        inform = ">(Importante)Primeiro Cadastre Funcionarios clicando no botão. \n"+
                 "Cada Classe tem 2 funcionarios cadastrados. \n"+
                 "O ID vai de 1 a 6. Sendo 2 por classe Ex. Gerente id: (1)(2); \n"+ 
                 "Operador (3)(4), Secretaria (5)(6);\n"+
                 ">Registrar Entrada:\n"+
                 "Crie um id ponto, para especificar o ponto, selecione a classe de \n"+ 
                 "funcionario e por ultimo o ID do funcionario daquela classe. \n"+
                 "Registre a Entrada.\n"+
                 ">Registrar Saida: \n"+
                 "Apenas digite o ID ponto criado o qual deseja registrar uma \n"+
                 "saída. \n"+
                 ">Listar Pontos: \n"+ 
                 "Ao clicar ele lista todos os pontos registrados no banco \n";
                 jTextArea1.setText(inform);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
 /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    public void cadGerente() {

        Gerente gerente1 = new Gerente();

        gerente1.setIdFunc(1);

        gerente1.setNome("Ze");

        gerente1.setEmail("ze@gmail.com");

        gerente1.setDocumento("7789987-0");

        gerente1.setLogin("Adm");

        gerente1.setSenha("1899");

        gerentes.add(gerente1);

        Gerente gerente2 = new Gerente();

        gerente2.setIdFunc(2);

        gerente2.setNome("Joao");

        gerente2.setEmail("joao@gmail.com");

        gerente2.setDocumento("7789987-0");

        gerente2.setLogin("Adm");

        gerente2.setSenha("1899");

        gerentes.add(gerente2);

    }

    public void cadSecretaria() {

        Secretaria secretaria1 = new Secretaria();

        secretaria1.setIdFunc(5);

        secretaria1.setNome("Juce");

        secretaria1.setEmail("juce@gmail.com");

        secretaria1.setDocumento("8780821-1");

        secretaria1.setTelefone("3866-1909");

        secretaria1.setRamal("i1129");

        secretarias.add(secretaria1);

        Secretaria secretaria2 = new Secretaria();

        secretaria2.setIdFunc(6);

        secretaria2.setNome("Jussevara");

        secretaria2.setEmail("jussevara@gmail.com");

        secretaria2.setDocumento("8780821-1");

        secretaria2.setTelefone("3866-1709");

        secretaria2.setRamal("i1128");

        secretarias.add(secretaria2);

    }

    public void cadOperdor() {

        Operador operador1 = new Operador();

        operador1.setIdFunc(3);

        operador1.setNome("Claudio");

        operador1.setEmail("claudio@gmail.com");

        operador1.setDocumento("8768767-0");

        operador1.setValorHora(120.5);

        operadores.add(operador1);

        Operador operador2 = new Operador();

        operador2.setIdFunc(4);

        operador2.setNome("Aurora");

        operador2.setEmail("aurora@gmail.com");

        operador2.setDocumento("878653-6");

        operador2.setValorHora(90.2);

        operadores.add(operador2);

    }

}
